version: '3.8'

services:
  # MySQL 数据库
  db:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: media_crawler_pro
    ports:
      - "37217:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mediacrawler-network
    command: --default-authentication-plugin=mysql_native_password

  # Redis 缓存和队列
  redis:
    image: registry.cn-shenzhen.aliyuncs.com/qjwwy-pro/redis:6.0.9
    container_name: redis_cache
    ports:
      - "32398:6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--requirepass", "123456"]
    restart: unless-stopped
    networks:
      - mediacrawler-network

  # PgVector 向量数据库
  pg:
    image: registry.cn-shenzhen.aliyuncs.com/qjwwy-pro/pgvector:v0.5.0
    container_name: pg
    ports:
      - "39432:5432"
    networks:
      - mediacrawler-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: FkaSjRGV7gynEMge
      POSTGRES_DB: postgres
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    restart: unless-stopped

# 不再需要 volumes 定义
# volumes:
#   mysql_db_data:
#   redis_data:

networks:
  mediacrawler-network:
    driver: bridge